apiVersion: v1
kind: Service
metadata:
  name: dke-db
  labels:
    app: dke-db
spec:
  clusterIP: None  # This makes the service headless (useful for StatefulSet)
  ports:
    - name: dke-db
      protocol: TCP
      port: 5432
      #port: 54325
      #targetPort: 5432
  selector:
    app: dke-db
  # type: NodePort